#!/bin/bash

CI_ENVIRONMENT=testing

CI_BUILD_NUMBER=$(($CI_BUILD_NUMBER + 175))
CI_BUILD_NAME=$CI_BUILD_NUMBER-$CI_ENVIRONMENT
npx trapeze run appflow.yml -y

echo CI_BUILD_NUMBER: $CI_BUILD_NUMBER
echo CI_BUILD_NAME: $CI_BUILD_NAME